algoritmo "Entrada e Saída de Dados"
// Função : Entrada e Saída de Dados
// Autor :  João Paulo Assis
// Data : 26/05/2020
// Seção de Declarações 
var
  nome: caracter
  nota: inteiro
inicio
// Seção de Comandos 
  escreva("Digite seu nome: ")
  leia(nome)
  escreva("Digite sua nota: ")
  leia(nota)
  
  escreval("O nome digitado foi: ", nome)
  escreval("A nota digitada foi: ", nota)
fimalgoritmo
