algoritmo "Estrutura-Para-Faça"
// Função : Estrutura Para-Faça
// Autor :  João Paulo Assis
// Data : 05/06/2020
// Seção de Declarações
var
 numero, fatorial, contador: inteiro
 
inicio
// Seção de Comandos

   escreva("Digite o número para calcular o fatorial: ")
   leia (numero)
   fatorial := 1
   para contador de 1 ate numero faca
        fatorial := fatorial  * contador
   fimpara
   escreva("O fatorial de ", numero, " é: ", fatorial)
fimalgoritmo
